language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - APP_DEBUG=false

install:
  - composer install --prefer-dist --optmize-autoloader --quiet

script: phpunit -c phpunit.xml --coverage-text